name: release
on:
  push:
    tags:
      - v*
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node: ['10.x']
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    
    - name: Set Node.js ${{ matrix.node }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm install

    - name: Vscode release plugin
      uses: sigma/vsce-publish-action@master
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      with:
        args: publish -p $VSCE_TOKEN
