name: release
on:
  push:
    tags:
      - v*
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node: ['18']
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm install

    - name: Vscode release plugin
      uses: lannonbr/vsce-action@4.0.0
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}